name: libsy_technical_assignment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.5.4

dependencies:
    flutter:
        sdk: flutter

    equatable: ^2.0.7
    http: ^1.2.2
    flutter_dotenv: ^5.2.1
    flutter_bloc: ^8.1.6
    flutter_screenutil: ^5.9.3
    fast_cached_network_image: ^1.2.9
    skeletonizer: ^1.4.3
    path_provider: ^2.1.5
    flutter_spinkit: ^5.2.1
    smooth_page_indicator: ^1.2.0+3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
        - assets/images/hoodie.png
        - assets/images/logo.png
        - assets/images/splash.png
        - assets/images/splash_light.png
        - assets/images/splash_b.png
